# Argonaut
# https://github.com/pwaleczek/Argonaut-theme

background = "#0e1019"
foreground = "#fffaf4"
cursor = "#ff761a"
cursor_text = "#0e1019"
selection_background = "#1c1e28"
selection_foreground = "#fffaf4"

black = "#232323"
red = "#ff000f"
green = "#8ce10b"
yellow = "#ffb900"
blue = "#008df8"
magenta = "#6d43a6"
cyan = "#00d8eb"
white = "#ffffff"

bright_black = "#444444"
bright_red = "#ff2740"
bright_green = "#abe15b"
bright_yellow = "#ffd242"
bright_blue = "#0092ff"
bright_magenta = "#9a5feb"
bright_cyan = "#67fff0"
bright_white = "#ffffff"
