[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-gnullvm]
rustflags = ["-C", "target-feature=+crt-static"]

[build]
# Use sccache if available
# rustc-wrapper = "sccache"

[alias]
xtask = "run --package xtask --"
